#
# Voltus Scheduler command file generated by voltus_rail on Wed Apr 16 00:12:46 2025
#
setvar log_file ./work/voltus_extractor.log
extracted_nets VDD 
setvar output_cache_directory_name /tmp/innovus_temp_25740_nc-csuaf4-l01.apporto.com_c11879_csufresno_tM809d/zx_tmp_nc-csuaf4-l01.apporto.com_6022
setvar library_name ./run1/era_work/incremental_output5/pgv/techonly.cl
setvar output_directory_name ./work
setvar output_file_name VDD
setvar max_error_messages 100
setvar max_resistor_length 800
setvar hierarchy_char /
layout_file /tmp/innovus_temp_25740_nc-csuaf4-l01.apporto.com_c11879_csufresno_tM809d/eps_out_25740.def.gz  
setvar exec_token "/tmp/innovus_temp_25740_nc-csuaf4-l01.apporto.com_c11879_csufresno_tM809d/eps_out_25740.def.gz"
setvar enable_signal_via_overhang false
setvar zx_multinet_extraction false
setvar extraction_mode early
setvar enable_zx_report_shorts true
extraction_type all none
extraction_type pattern VDD r_only
hierarchical_path_tracer netinst_table ./work/VDD.netinst
hierarchical_path_tracer cell_table ./work/VDD.cellinst
setvar output_wlt drawn
setvar use_hpt_leqnets_info true
label port VDDvsrc1 339.2050 245.2150 metal10
label port VDDvsrc2 4.0500 208.7850 metal10
hierarchical_path_tracer pgnet_table ./work/all.pgnets
setvar output_def false
setvar cluster_via_size 25
setvar cluster_via1_maximum true
setvar def_merge_supply_shorts false
setvar promote_ports true
setvar max_cpu 1
setvar tech_file QRC_Tech/gpdk045.tch
setvar density_check_method database
setvar sfedb_path ./work/SFEDB 
setvar enable_binary_inst_pgdb true
setvar keep_log_file false
